version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      POSTGRES_USER: ${POSTGRES_DB_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: on-failure
    networks:
      - not-booking

  overview-ms:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_DB_PASSWORD}
    networks:
      - not-booking

volumes:
  postgres_data:

networks:
  not-booking: